"""
Placeholder sync script.

The real implementation is generated by the platform sync skill that matches
the platform field in course-config.yaml. For example:
  - platform: thinkific  -> sync/thinkific skill writes the real sync.py
  - platform: canvas     -> sync/canvas skill writes the real sync.py

Until the platform sync skill runs, this file is a placeholder. Running it
will print a helpful message and exit.
"""

import sys


def main():
    print("This is a placeholder sync.py.")
    print()
    print("Run the platform sync skill from the toolkit to generate the real")
    print("implementation. From your terminal in the toolkit folder:")
    print()
    print("  claude")
    print()
    print("Then ask Claude Code to run the sync skill that matches the platform")
    print("field in your course-config.yaml.")
    print()
    print("Or, once bes is installed, use:")
    print()
    print("  bes sync")
    print()
    sys.exit(0)


if __name__ == "__main__":
    main()
