"""
Placeholder validate script.

The real implementation is generated by the course-validator skill (Phase 5).
Until then, this file does basic sanity checks and exits.
"""

import sys
from pathlib import Path

import yaml


def main():
    repo_root = Path(__file__).parent.parent
    issues = []

    # Check course-config.yaml exists and parses
    config_path = repo_root / "course-config.yaml"
    if not config_path.exists():
        issues.append("course-config.yaml is missing.")
    else:
        try:
            with config_path.open() as f:
                yaml.safe_load(f)
        except yaml.YAMLError as e:
            issues.append(f"course-config.yaml does not parse: {e}")

    # Check course-description.md exists
    desc_path = repo_root / "course-description.md"
    if not desc_path.exists():
        issues.append("course-description.md is missing.")
    elif desc_path.stat().st_size < 100:
        issues.append("course-description.md looks empty or unfilled.")

    # Check content/ folder has at least one unit
    content_dir = repo_root / "content"
    if not content_dir.exists():
        issues.append("content/ folder is missing.")
    elif not any(content_dir.glob("unit-*")):
        issues.append("content/ has no unit folders.")

    if issues:
        print("Validation found issues:")
        for issue in issues:
            print(f"  - {issue}")
        sys.exit(1)

    print("Basic validation passed.")
    print("(The full course-validator skill from the toolkit catches more issues.)")
    sys.exit(0)


if __name__ == "__main__":
    main()
